parameters:
    ebay_client_id: '%env(EBAY_CLIENT_ID)%'
    ebay_client_secret: '%env(EBAY_CLIENT_SECRET)%'
    ebay_redirect_uri: '%env(EBAY_REDIRECT_URI)%'
    ebay_scoope: '%env(EBAY_SCOPES)%'
    ebay_environment: '%env(EBAY_ENVIRONMENT)%'

services:

    GuzzleHttp\Client:
        class: GuzzleHttp\Client
        arguments:
            $config: [] 

    _defaults:
        autowire: true      
        autoconfigure: true 

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

